### ISSUE TITLE
Can't download from Google Drive

### ISSUE THREAD

**Issue by ahblahblah** [gutris1/sd-hub#13]
So the extension generally works really well, but recently when trying to install gdrive links, I get the following error:
`Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1117, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 350, in async_iteration
    return await iterator.__anext__()
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 343, in __anext__
    return await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 326, in run_sync_iterator_async
    return next(iterator)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 695, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/content/sdw/extensions/sd-hub/sd_hub/downloader.py", line 332, in downloader
    for _text, _flag in surface(command, token2, token3):
  File "/content/sdw/extensions/sd-hub/sd_hub/downloader.py", line 314, in surface
    for message, isError in gdrown(url, target_path, fn):
  File "/content/sdw/extensions/sd-hub/sd_hub/downloader.py", line 21, in gdrown
    p = subprocess.Popen(
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/gdown'

`

**Comment by gutris1** [comment]
what is gdrive links ?

the error 'FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/gdown'
is missing the gdown package itself, but it should automatically install when the webui is launching
what is going on here

**Comment by ahblahblah** [comment]
>what is gdrive links ?

Google Drive. Weirdly, this worked just fine a while ago, and links from huggingface or civitai work just fine.

**Comment by gutris1** [comment]
> > what is gdrive links ?
> 
> Google Drive. Weirdly, this worked just fine a while ago, and links from huggingface or civitai work just fine.

try to manually install gdown with pip install gdown
does that solve it

**Comment by barracuda500GB** [comment]
i got similar error too, cant download any link

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1117, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 350, in async_iteration
    return await iterator.__anext__()
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 343, in __anext__
    return await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 326, in run_sync_iterator_async
    return next(iterator)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 695, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/root/sdw/extensions/HUB/sd_hub/downloader.py", line 332, in downloader
    for _text, _flag in surface(command, token2, token3):
  File "/root/sdw/extensions/HUB/sd_hub/downloader.py", line 318, in surface
    for output in ariari(
  File "/root/sdw/extensions/HUB/sd_hub/downloader.py", line 129, in ariari
    p = subprocess.Popen(
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/aria2c'

**Comment by gutris1** [comment]
so it was google colab huh

**Comment by gutris1** [comment]
where you get the notebook?
I've to try that in google colab

**Comment by gutris1** [comment]
it fixed now.

**Comment by SonicSaber** [comment]
> it fixed now.

ah finally
I wonder why it work on kaggle but not on google colab
thank you very much!

**Comment by gutris1** [comment]
> > it fixed now.
> 
> ah finally I wonder why it work on kaggle but not on google colab thank you very much!

I dont use colab, so I dont even test the extension using google colab
