### ISSUE TITLE
Not show up in the tabs 

### ISSUE THREAD

**Issue by metapea** [gutris1/sd-hub#9]
Unlike sd-model-downloader, sd-hub doesn't show up in the tabs on forge
Also I've been getting this error when starting up:
```
Installing requirements for CivitAI Browser
*** Error running install.py for extension X:\forge\webui\extensions\sd-hub.
*** Command: "X:\forge\system\python\python.exe" "X:\forge\webui\extensions\sd-hub\install.py"
*** Error code: 1
*** stderr: Traceback (most recent call last):
***   File "X:\forge\webui\extensions\sd-hub\install.py", line 135, in <module>
***     _install_req_2()
***   File "X:\forge\webui\extensions\sd-hub\install.py", line 118, in _install_req_2
***     if _sub(['apt', pkg_cmds['apt']]):
***   File "X:\forge\webui\extensions\sd-hub\install.py", line 17, in _sub
***     subprocess.run(
***   File "subprocess.py", line 501, in run
***   File "subprocess.py", line 969, in __init__
***   File "subprocess.py", line 1438, in _execute_child
*** FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by gutris1** [comment]
it won't work on local windows
